# Generated by Django 4.2.30 on 2026-06-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, help_text='Cole a URL completa do YouTube (ex: https://www.youtube.com/watch?v=XXXXX)', verbose_name='URL do YouTube'),
        ),
    ]
