# Generated by Django 4.2.30 on 2026-07-21 02:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="Slug"
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço (R$)"
                    ),
                ),
                (
                    "duracao_minutos",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Duração (min)"
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="🔮", max_length=10, verbose_name="Ícone (emoji)"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Tipo de Consulta",
                "verbose_name_plural": "Tipos de Consulta",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referencia",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Referência",
                    ),
                ),
                ("nome_cliente", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "email_cliente",
                    models.EmailField(max_length=254, verbose_name="E-mail"),
                ),
                (
                    "whatsapp_cliente",
                    models.CharField(max_length=30, verbose_name="WhatsApp"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Aguardando pagamento"),
                            ("aprovado", "Pago"),
                            ("rejeitado", "Recusado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "mp_preference_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID da preferência (Mercado Pago)",
                    ),
                ),
                (
                    "mp_payment_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID do pagamento (Mercado Pago)",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "tipo_consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas",
                        to="consultas.tipoconsulta",
                        verbose_name="Tipo de consulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ["-criado_em"],
            },
        ),
    ]
