# Generated by Django 4.2.30 on 2026-08-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='pagamento_divergente',
            field=models.BooleanField(default=False, verbose_name='Pagamento com valor divergente'),
        ),
    ]
